Added responsive logo & misc
kaspher/TrailMates pull request #41
Opened 2024-11-14 16:01 UTC by bezi19

responsive logo, user avatar, colors change and register text change

2024-11-15 21:57 UTC, kaspher requested changes
🔥

2024-11-15 21:57 UTC, kaspher commented on frontend/src/components/pages/Layout.js
> +import logoUrl2 from "../../assets/img/logo/logo.svg"
zmień to może na coś w stulu LogoUrlMobile?

2024-11-15 21:57 UTC, kaspher commented on frontend/src/assets/css/colors.scss
> +$primary-color: #386641;
dodaj to do `tailwind.config.js`

2024-11-15 21:57 UTC, kaspher commented on frontend/src/components/pages/Layout.js
> +                    src={user ? cloudFrontDomainName + user.id : userAvatar}
wywal to userAvatar, default bedzie brany z `aws s3`

2024-11-15 21:57 UTC, kaspher commented on frontend/src/components/pages/auth/Register.js
> +            Zaloguj się tutaj!
👍🏽

2024-11-21 12:05 UTC, bezi19 commented
fixed

2024-11-24 17:07 UTC, merged